### ISSUE TITLE
panic: standard_init_linux.go:178: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by kodi1981** [myENA/consul-backinator#44]
We are getting this error with consul:1.2.1 docker consul & backinator 1.6.5

panic: standard_init_linux.go:178: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
github.com/urfave/cli.HandleAction.func1(0xc4200a17a0)
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x23f
panic(0x6f0cc0, 0xc42011d5e0)
	/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc4200a1208, 0xc42000e0d0, 0xc4200a12a8)
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0xc1
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc4200509b0, 0xaa88e0, 0xc42011d5e0)
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x353
main.glob..func8(0xc42007c780, 0x0, 0x0)
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/main_unix.go:26 +0x66
reflect.Value.call(0x6d9be0, 0x750350, 0x13, 0x73b942, 0x4, 0xc4200a1760, 0x1, 0x1, 0xc4200a16f0, 0x731420, ...)
	/usr/lib/golang/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x6d9be0, 0x750350, 0x13, 0xc4200a1760, 0x1, 0x1, 0x665b36, 0x73bace, 0x4)
	/usr/lib/golang/src/reflect/value.go:302 +0xa4
github.com/urfave/cli.HandleAction(0x6d9be0, 0x750350, 0xc42007c780, 0x0, 0x0)
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x18f
github.com/urfave/cli.Command.Run(0x73baee, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x74d391, 0x51, 0x0, ...)
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xac8
github.com/urfave/cli.(*App).Run(0xc4200aa000, 0xc42000c140, 0x2, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x5d6
main.main()
	/builddir/build/BUILD/docker-ec8512ba42f349cbe5a63140c4d9c810f7afa527/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/main.go:137 +0xbd2

**Comment by leprechau** [comment]
This error is coming from Docker not consul-backinator.  Have you modified the Dockerfile or changed the entrypoint and/or command for the published image?

**Comment by kodi1981** [comment]
Thanks let me check my entrypoint.

**Comment by leprechau** [comment]
Closing due to inactivity.  Please feel free to re-open if this is still an issue.
